// This file is generated by the createModsData.js script.
// Do not manually make changes to this file because they will be overridden
// This file uses a custom data structure specific to the Mods page

export default [
  {
    name: "Armor Mods",
    sets: [
      {
        name: "Helmet",
        big: false,
        sections: [
          {
            name: "Any",
            nameHash: 1198124803,
            itemGroups: [
              [
                3213968580 // Enhanced Scatter Projectile Targeting
              ],
              [
                3786078704, // Precision Weapon Targeting
                3476502793 // Scatter Projectile Targeting
              ],
              [
                3068122505, // Primary Ammo Finder
                1041574086, // Special Ammo Finder
                3091871970 // Heavy Ammo Finder
              ]
            ],
            groups: [
              {
                name: "Seasonal Artifact mod",
                items: [
                  3213968580 // Enhanced Scatter Projectile Targeting
                ]
              },
              {
                name: "Targeting",
                items: [
                  3786078704, // Precision Weapon Targeting
                  3476502793 // Scatter Projectile Targeting
                ]
              },
              {
                name: "Ammo Finder",
                items: [
                  3068122505, // Primary Ammo Finder
                  1041574086, // Special Ammo Finder
                  3091871970 // Heavy Ammo Finder
                ]
              }
            ]
          },
          {
            name: "Arc",
            nameHash: 728351493,
            itemGroups: [
              [
                1624081088, // Bow Ammo Finder
                2128395292, // Machine Gun Ammo Finder
                589699896, // Pulse Rifle Ammo Finder
                4148827738, // Shotgun Ammo Finder
                1476367343 // Sword Ammo Finder
              ],
              [
                2080519917, // Bow Targeting
                3993244252, // Enhanced Bow Targeting
                1015337793, // Machine Gun Targeting
                3319681729, // Pulse Rifle Targeting
                2919349723, // Shotgun Targeting
                3309247652, // Enhanced Machine Gun Targeting
                1248126076, // Enhanced Pulse Rifle Targeting
                4190395210 // Enhanced Shotgun Targeting
              ]
            ],
            groups: [
              {
                name: "Ammo Finder",
                items: [
                  1624081088, // Bow Ammo Finder
                  2128395292, // Machine Gun Ammo Finder
                  589699896, // Pulse Rifle Ammo Finder
                  4148827738, // Shotgun Ammo Finder
                  1476367343 // Sword Ammo Finder
                ]
              },
              {
                name: "Targeting",
                items: [
                  2080519917, // Bow Targeting
                  3993244252, // Enhanced Bow Targeting
                  1015337793, // Machine Gun Targeting
                  3319681729, // Pulse Rifle Targeting
                  2919349723, // Shotgun Targeting
                  3309247652, // Enhanced Machine Gun Targeting
                  1248126076, // Enhanced Pulse Rifle Targeting
                  4190395210 // Enhanced Shotgun Targeting
                ]
              }
            ]
          },
          {
            name: "Solar",
            nameHash: 591714140,
            itemGroups: [
              [
                2193892158, // Auto Rifle Ammo Finder
                3394151347, // Fusion Rifle Ammo Finder
                1499759470, // Linear Fusion Rifle Ammo Finder
                2603856295, // Rocket Launcher Ammo Finder
                1588113119 // Submachine Gun Ammo Finder
              ],
              [
                3201675491, // Auto Rifle Targeting
                3901392720, // Fusion Rifle Targeting
                3338875786, // Linear Fusion Rifle Targeting
                1627441143, // Enhanced Linear Fusion Targeting
                3857411140, // Submachine Gun Targeting
                1758950396, // Enhanced Auto Rifle Targeting
                87259167, // Enhanced Fusion Rifle Targeting
                2847540257 // Enhanced Submachine Gun Targeting
              ]
            ],
            groups: [
              {
                name: "Ammo Finder",
                items: [
                  2193892158, // Auto Rifle Ammo Finder
                  3394151347, // Fusion Rifle Ammo Finder
                  1499759470, // Linear Fusion Rifle Ammo Finder
                  2603856295, // Rocket Launcher Ammo Finder
                  1588113119 // Submachine Gun Ammo Finder
                ]
              },
              {
                name: "Targeting",
                items: [
                  3201675491, // Auto Rifle Targeting
                  3901392720, // Fusion Rifle Targeting
                  3338875786, // Linear Fusion Rifle Targeting
                  1627441143, // Enhanced Linear Fusion Targeting
                  3857411140, // Submachine Gun Targeting
                  1758950396, // Enhanced Auto Rifle Targeting
                  87259167, // Enhanced Fusion Rifle Targeting
                  2847540257 // Enhanced Submachine Gun Targeting
                ]
              }
            ]
          },
          {
            name: "Void",
            nameHash: 4069572561,
            itemGroups: [
              [
                755265365, // Grenade Launcher Ammo Finder
                650047261, // Hand Cannon Ammo Finder
                421111969, // Scout Rifle Ammo Finder
                1050260245, // Sidearm Ammo Finder
                2754084930 // Sniper Rifle Ammo Finder
              ],
              [
                2829974286, // Hand Cannon Targeting
                1871240627, // Enhanced Hand Cannon Targeting
                631976966, // Scout Rifle Targeting
                1507854082, // Sidearm Targeting
                2307244871, // Sniper Rifle Targeting
                198889228, // Enhanced Sniper Rifle Targeting
                130615063, // Enhanced Scout Rifle Targeting
                3178987263 // Enhanced Sidearm Targeting
              ]
            ],
            groups: [
              {
                name: "Ammo Finder",
                items: [
                  755265365, // Grenade Launcher Ammo Finder
                  650047261, // Hand Cannon Ammo Finder
                  421111969, // Scout Rifle Ammo Finder
                  1050260245, // Sidearm Ammo Finder
                  2754084930 // Sniper Rifle Ammo Finder
                ]
              },
              {
                name: "Targeting",
                items: [
                  2829974286, // Hand Cannon Targeting
                  1871240627, // Enhanced Hand Cannon Targeting
                  631976966, // Scout Rifle Targeting
                  1507854082, // Sidearm Targeting
                  2307244871, // Sniper Rifle Targeting
                  198889228, // Enhanced Sniper Rifle Targeting
                  130615063, // Enhanced Scout Rifle Targeting
                  3178987263 // Enhanced Sidearm Targeting
                ]
              }
            ]
          }
        ]
      },
      {
        name: "Arms",
        big: false,
        sections: [
          {
            name: "Any",
            nameHash: 1198124803,
            itemGroups: [
              [
                3213968582, // Enhanced Pulse Rifle Loader
                3213968578, // Enhanced Bow Loader
                3175764267 // Unstoppable Pulse Rifle
              ],
              [
                403494087 // Fastball
              ],
              [
                575217150, // Light Arms Loader
                4146282118, // Rifle Loader
                3493464614 // Large Weapon Loader
              ]
            ],
            groups: [
              {
                name: "Seasonal Artifact mod",
                items: [
                  3213968582, // Enhanced Pulse Rifle Loader
                  3213968578, // Enhanced Bow Loader
                  3175764267 // Unstoppable Pulse Rifle
                ]
              },
              {
                name: "General",
                items: [
                  403494087 // Fastball
                ]
              },
              {
                name: "Loaders",
                items: [
                  575217150, // Light Arms Loader
                  4146282118, // Rifle Loader
                  3493464614 // Large Weapon Loader
                ]
              }
            ]
          },
          {
            name: "Arc",
            nameHash: 728351493,
            itemGroups: [
              [
                3470562293, // Impact Induction
                774147760 // Enhanced Impact Induction
              ],
              [
                3436675785, // Bow Reloader
                157329321, // Machine Gun Loader
                1129724921, // Pulse Rifle Loader
                1534061443, // Shotgun Loader
                1657427196, // Enhanced Shotgun Loader
                2599026044, // Enhanced Bow Loader
                3661789072, // Enhanced Machine Gun Loader
                38612140 // Enhanced Pulse Rifle Loader
              ]
            ],
            groups: [
              {
                name: "General",
                items: [
                  3470562293, // Impact Induction
                  774147760 // Enhanced Impact Induction
                ]
              },
              {
                name: "Loaders",
                items: [
                  3436675785, // Bow Reloader
                  157329321, // Machine Gun Loader
                  1129724921, // Pulse Rifle Loader
                  1534061443, // Shotgun Loader
                  1657427196, // Enhanced Shotgun Loader
                  2599026044, // Enhanced Bow Loader
                  3661789072, // Enhanced Machine Gun Loader
                  38612140 // Enhanced Pulse Rifle Loader
                ]
              }
            ]
          },
          {
            name: "Solar",
            nameHash: 591714140,
            itemGroups: [
              [
                3788210493, // Momentum Transfer
                531981182 // Enhanced Momentum Transfer
              ],
              [
                2571974065, // Auto Rifle Loader
                428274928, // Fusion Rifle Loader
                178399816, // Linear Fusion Rifle Loader
                2324400338, // Rocket Launcher Loader
                503582313, // Enhanced Rocket Launcher Loader
                2790645726, // Submachine Gun Loader
                4258747542, // Enhanced Auto Rifle Loader
                1318561067, // Enhanced Fusion Rifle Loader
                2818043025, // Enhanced Linear Fusion Rifle Loader
                1823641159 // Enhanced Submachine Gun Loader
              ]
            ],
            groups: [
              {
                name: "General",
                items: [
                  3788210493, // Momentum Transfer
                  531981182 // Enhanced Momentum Transfer
                ]
              },
              {
                name: "Loaders",
                items: [
                  2571974065, // Auto Rifle Loader
                  428274928, // Fusion Rifle Loader
                  178399816, // Linear Fusion Rifle Loader
                  2324400338, // Rocket Launcher Loader
                  503582313, // Enhanced Rocket Launcher Loader
                  2790645726, // Submachine Gun Loader
                  4258747542, // Enhanced Auto Rifle Loader
                  1318561067, // Enhanced Fusion Rifle Loader
                  2818043025, // Enhanced Linear Fusion Rifle Loader
                  1823641159 // Enhanced Submachine Gun Loader
                ]
              }
            ]
          },
          {
            name: "Void",
            nameHash: 4069572561,
            itemGroups: [
              [
                4140815674, // Grenade Launcher Loader
                2165754723, // Enhanced Grenade Launcher Loader
                1052494884, // Hand Cannon Loader
                989778135, // Enhanced Hand Cannon Loader
                667313240, // Scout Rifle Loader
                762238512, // Sidearm Loader
                2039949393, // Sniper Rifle Loader
                3282442165, // Enhanced Scout Rifle Loader
                361808353, // Enhanced Sidearm Loader
                2163041754 // Enhanced Sniper Rifle Loader
              ]
            ],
            groups: [
              {
                name: "Loaders",
                items: [
                  4140815674, // Grenade Launcher Loader
                  2165754723, // Enhanced Grenade Launcher Loader
                  1052494884, // Hand Cannon Loader
                  989778135, // Enhanced Hand Cannon Loader
                  667313240, // Scout Rifle Loader
                  762238512, // Sidearm Loader
                  2039949393, // Sniper Rifle Loader
                  3282442165, // Enhanced Scout Rifle Loader
                  361808353, // Enhanced Sidearm Loader
                  2163041754 // Enhanced Sniper Rifle Loader
                ]
              }
            ]
          }
        ]
      },
      {
        name: "Chest",
        big: false,
        sections: [
          {
            name: "Any",
            nameHash: 1198124803,
            itemGroups: [
              [
                3213968581, // Enhanced Unflinching Rifle Aim
                3175764264, // Counter Charge
                3175764266, // Overload Grenades
                3175764269, // Breach Resonator
                3175764268 // Inferno Whip
              ],
              [
                1541497724, // Unflinching Light Arms Aim
                3084181312, // Unflinching Rifle Aim
                364819640 // Unflinching Large Arms
              ],
              [
                2020900991, // Light Arms Reserves
                3397262883, // Large Arms Reserves
                1384818155 // Rifle Reserves
              ]
            ],
            groups: [
              {
                name: "Seasonal Artifact mod",
                items: [
                  3213968581, // Enhanced Unflinching Rifle Aim
                  3175764264, // Counter Charge
                  3175764266, // Overload Grenades
                  3175764269, // Breach Resonator
                  3175764268 // Inferno Whip
                ]
              },
              {
                name: "Unflinching aim",
                items: [
                  1541497724, // Unflinching Light Arms Aim
                  3084181312, // Unflinching Rifle Aim
                  364819640 // Unflinching Large Arms
                ]
              },
              {
                name: "Ammo Reserves",
                items: [
                  2020900991, // Light Arms Reserves
                  3397262883, // Large Arms Reserves
                  1384818155 // Rifle Reserves
                ]
              }
            ]
          },
          {
            name: "Arc",
            nameHash: 728351493,
            itemGroups: [
              [
                201502208, // Bow Reserves
                3188535145, // Machine Gun Reserves
                1478123840, // Pulse Rifle Reserves
                2368162286, // Shotgun Reserves
                3543966269 // Sword Reserves
              ],
              [
                3662638763, // Unflinching Bow Aim
                643703876, // Enhanced Unflinching Bow Aim
                3091213995, // Unflinching Machine Gun
                2379452959, // Unflinching Pulse Rifle Aim
                357349821, // Unflinching Shotgun Aim
                476007934, // Enhanced Unflinching Machine Gun Aim
                2066320542, // Enhanced Unflinching Pulse Rifle Aim
                2998471416 // Enhanced Unflinching Shotgun Aim
              ]
            ],
            groups: [
              {
                name: "Ammo Reserves",
                items: [
                  201502208, // Bow Reserves
                  3188535145, // Machine Gun Reserves
                  1478123840, // Pulse Rifle Reserves
                  2368162286, // Shotgun Reserves
                  3543966269 // Sword Reserves
                ]
              },
              {
                name: "Unflinching aim",
                items: [
                  3662638763, // Unflinching Bow Aim
                  643703876, // Enhanced Unflinching Bow Aim
                  3091213995, // Unflinching Machine Gun
                  2379452959, // Unflinching Pulse Rifle Aim
                  357349821, // Unflinching Shotgun Aim
                  476007934, // Enhanced Unflinching Machine Gun Aim
                  2066320542, // Enhanced Unflinching Pulse Rifle Aim
                  2998471416 // Enhanced Unflinching Shotgun Aim
                ]
              }
            ]
          },
          {
            name: "Solar",
            nameHash: 591714140,
            itemGroups: [
              [
                1131497704, // Auto Rifle Reserves
                3531950723, // Fusion Rifle Reserves
                749060462, // Linear Fusion Rifle Reserves
                1303690937, // Rocket Launcher Reserves
                1829115845 // Submachine Gun Reserves
              ],
              [
                2505824339, // Unflinching Auto Rifle Aim
                3121039270, // Unflinching Fusion Rifle Aim
                650627622, // Unflinching Linear Fusion Aim
                3673056113, // Enhanced Unflinching Linear Fusion Aim
                3626376648, // Unflinching Submachine Gun Aim
                2568247584, // Enhanced Unflinching Auto Rifle Aim
                4057143977, // Enhanced Unflinching Fusion Rifle Aim
                1008801629 // Enhanced Unflinching Submachine Gun Aim
              ]
            ],
            groups: [
              {
                name: "Ammo Reserves",
                items: [
                  1131497704, // Auto Rifle Reserves
                  3531950723, // Fusion Rifle Reserves
                  749060462, // Linear Fusion Rifle Reserves
                  1303690937, // Rocket Launcher Reserves
                  1829115845 // Submachine Gun Reserves
                ]
              },
              {
                name: "Unflinching aim",
                items: [
                  2505824339, // Unflinching Auto Rifle Aim
                  3121039270, // Unflinching Fusion Rifle Aim
                  650627622, // Unflinching Linear Fusion Aim
                  3673056113, // Enhanced Unflinching Linear Fusion Aim
                  3626376648, // Unflinching Submachine Gun Aim
                  2568247584, // Enhanced Unflinching Auto Rifle Aim
                  4057143977, // Enhanced Unflinching Fusion Rifle Aim
                  1008801629 // Enhanced Unflinching Submachine Gun Aim
                ]
              }
            ]
          },
          {
            name: "Void",
            nameHash: 4069572561,
            itemGroups: [
              [
                3330921441, // Grenade Launcher Reserves
                1043617959, // Hand Cannon Reserves
                240987419, // Scout Rifle Reserves
                3859610803, // Sidearm Reserves
                3926976952 // Sniper Rifle Reserves
              ],
              [
                807774340, // Unflinching Grenade Launcher Aim
                1859929470, // Unflinching Hand Cannon Aim
                1279446438, // Unflinching Scout Rifle Aim
                263996333, // Enhanced Unflinching Scout Rifle Aim
                2881057950, // Unflinching Sidearm Aim
                1203395203, // Unflinching Sniper Aim
                435979054, // Enhanced Unflinching Sniper Aim
                1582133419, // Enhanced Unflinching Grenade Launcher Aim
                262997143, // Enhanced Unflinching Hand Cannon Aim
                3234602043 // Enhanced Unflinching Sidearm Aim
              ]
            ],
            groups: [
              {
                name: "Ammo Reserves",
                items: [
                  3330921441, // Grenade Launcher Reserves
                  1043617959, // Hand Cannon Reserves
                  240987419, // Scout Rifle Reserves
                  3859610803, // Sidearm Reserves
                  3926976952 // Sniper Rifle Reserves
                ]
              },
              {
                name: "Unflinching aim",
                items: [
                  807774340, // Unflinching Grenade Launcher Aim
                  1859929470, // Unflinching Hand Cannon Aim
                  1279446438, // Unflinching Scout Rifle Aim
                  263996333, // Enhanced Unflinching Scout Rifle Aim
                  2881057950, // Unflinching Sidearm Aim
                  1203395203, // Unflinching Sniper Aim
                  435979054, // Enhanced Unflinching Sniper Aim
                  1582133419, // Enhanced Unflinching Grenade Launcher Aim
                  262997143, // Enhanced Unflinching Hand Cannon Aim
                  3234602043 // Enhanced Unflinching Sidearm Aim
                ]
              }
            ]
          }
        ]
      },
      {
        name: "Legs",
        big: false,
        sections: [
          {
            name: "Any",
            nameHash: 1198124803,
            itemGroups: [
              [
                3465659109, // Flourishing Blade
                3465659111, // Automatic Prize
                3465659104, // Dimensional Tithes
                3465659105, // Ascendant Bounty
                3213968579 // Enhanced Sword Scavenger
              ],
              [
                1708067044 // Traction
              ],
              [
                805625272, // Light Arms Dexterity
                3507619526, // Rifle Dexterity
                3175015261 // Oversize Weapon Dexterity
              ],
              [
                2401086340, // Primary Ammo Scavenger
                345205583, // Special Ammo Scavenger
                3866072732 // Heavy Ammo Scavenger
              ]
            ],
            groups: [
              {
                name: "Seasonal Artifact mod",
                items: [
                  3465659109, // Flourishing Blade
                  3465659111, // Automatic Prize
                  3465659104, // Dimensional Tithes
                  3465659105, // Ascendant Bounty
                  3213968579 // Enhanced Sword Scavenger
                ]
              },
              {
                name: "General",
                items: [
                  1708067044 // Traction
                ]
              },
              {
                name: "Dexterity",
                items: [
                  805625272, // Light Arms Dexterity
                  3507619526, // Rifle Dexterity
                  3175015261 // Oversize Weapon Dexterity
                ]
              },
              {
                name: "Ammo Scavenger",
                items: [
                  2401086340, // Primary Ammo Scavenger
                  345205583, // Special Ammo Scavenger
                  3866072732 // Heavy Ammo Scavenger
                ]
              }
            ]
          },
          {
            name: "Arc",
            nameHash: 728351493,
            itemGroups: [
              [
                987267082, // Arrow Scavenger
                1559280270, // Machine Gun Scavenger
                3156855054, // Pulse Rifle Scavenger
                3836152936, // Shotgun Scavenger
                2146553541 // Sword Scavenger
              ],
              [
                3296399440, // Bow Dexterity
                3362003312, // Machine Gun Dexterity
                691818084, // Pulse Rifle Dexterity
                2561450986, // Shotgun Dexterity
                294409479, // Enhanced Shotgun Dexterity
                768133715, // Enhanced Bow Dexterity
                1993219983, // Enhanced Machine Gun Dexterity
                727582839 // Enhanced Pulse Rifle Dexterity
              ]
            ],
            groups: [
              {
                name: "Ammo Scavenger",
                items: [
                  987267082, // Arrow Scavenger
                  1559280270, // Machine Gun Scavenger
                  3156855054, // Pulse Rifle Scavenger
                  3836152936, // Shotgun Scavenger
                  2146553541 // Sword Scavenger
                ]
              },
              {
                name: "Dexterity",
                items: [
                  3296399440, // Bow Dexterity
                  3362003312, // Machine Gun Dexterity
                  691818084, // Pulse Rifle Dexterity
                  2561450986, // Shotgun Dexterity
                  294409479, // Enhanced Shotgun Dexterity
                  768133715, // Enhanced Bow Dexterity
                  1993219983, // Enhanced Machine Gun Dexterity
                  727582839 // Enhanced Pulse Rifle Dexterity
                ]
              }
            ]
          },
          {
            name: "Solar",
            nameHash: 591714140,
            itemGroups: [
              [
                737634704, // Auto Rifle Scavenger
                2347686425, // Fusion Rifle Scavenger
                2051366208, // Linear Fusion Rifle Scavenger
                311492789, // Rocket Launcher Scavenger
                1023632589 // Submachine Gun Scavenger
              ],
              [
                1312062056, // Auto Rifle Dexterity
                945523359, // Fusion Rifle Dexterity
                2520883911, // Linear Fusion Dexterity
                3026352437, // Rocket Launcher Dexterity
                3076533032, // Enhanced Rocket Launcher Dexterity
                201274281, // Submachine Gun Dexterity
                2912791105, // Enhanced Auto Rifle Dexterity
                206913198, // Enhanced Fusion Rifle Dexterity
                1472121496, // Enhanced Linear Fusion Rifle Dexterity
                4085860898 // Enhanced Submachine Gun Dexterity
              ]
            ],
            groups: [
              {
                name: "Ammo Scavenger",
                items: [
                  737634704, // Auto Rifle Scavenger
                  2347686425, // Fusion Rifle Scavenger
                  2051366208, // Linear Fusion Rifle Scavenger
                  311492789, // Rocket Launcher Scavenger
                  1023632589 // Submachine Gun Scavenger
                ]
              },
              {
                name: "Dexterity",
                items: [
                  1312062056, // Auto Rifle Dexterity
                  945523359, // Fusion Rifle Dexterity
                  2520883911, // Linear Fusion Dexterity
                  3026352437, // Rocket Launcher Dexterity
                  3076533032, // Enhanced Rocket Launcher Dexterity
                  201274281, // Submachine Gun Dexterity
                  2912791105, // Enhanced Auto Rifle Dexterity
                  206913198, // Enhanced Fusion Rifle Dexterity
                  1472121496, // Enhanced Linear Fusion Rifle Dexterity
                  4085860898 // Enhanced Submachine Gun Dexterity
                ]
              }
            ]
          },
          {
            name: "Void",
            nameHash: 4069572561,
            itemGroups: [
              [
                3670960347, // Grenade Launcher Scavenger
                2758832455, // Hand Cannon Scavenger
                356666687, // Scout Rifle Scavenger
                2183342667, // Sidearm Scavenger
                498878196 // Sniper Rifle Scavenger
              ],
              [
                2214082005, // Grenade Launcher Dexterity
                3484440775, // Hand Cannon Dexterity
                23817334, // Enhanced Hand Cannon Dexterity
                327265103, // Scout Rifle Dexterity
                101023751, // Sidearm Dexterity
                1819979056, // Sniper Rifle Dexterity
                439107567, // Enhanced Sniper Rifle Dexterity
                358728248, // Enhanced Grenade Launcher Dexterity
                4235763716, // Enhanced Scout Rifle Dexterity
                2620269144 // Enhanced Sidearm Dexterity
              ]
            ],
            groups: [
              {
                name: "Ammo Scavenger",
                items: [
                  3670960347, // Grenade Launcher Scavenger
                  2758832455, // Hand Cannon Scavenger
                  356666687, // Scout Rifle Scavenger
                  2183342667, // Sidearm Scavenger
                  498878196 // Sniper Rifle Scavenger
                ]
              },
              {
                name: "Dexterity",
                items: [
                  2214082005, // Grenade Launcher Dexterity
                  3484440775, // Hand Cannon Dexterity
                  23817334, // Enhanced Hand Cannon Dexterity
                  327265103, // Scout Rifle Dexterity
                  101023751, // Sidearm Dexterity
                  1819979056, // Sniper Rifle Dexterity
                  439107567, // Enhanced Sniper Rifle Dexterity
                  358728248, // Enhanced Grenade Launcher Dexterity
                  4235763716, // Enhanced Scout Rifle Dexterity
                  2620269144 // Enhanced Sidearm Dexterity
                ]
              }
            ]
          }
        ]
      },
      {
        name: "Class item",
        big: false,
        sections: [
          {
            name: "Any",
            nameHash: 1198124803,
            itemGroups: [
              [
                4186620519, // Oppressive Darkness
                4186620516, // Solar Plexus
                4186620517, // Heavy Finisher
                4186620514, // Volatile Conduction
                4186620515 // Guardian Angel
              ],
              [
                3320641683, // Absolution
                1513970148, // Distribution
                4237638090, // Special Finisher
                4237638094 // Snapload Finisher
              ]
            ],
            groups: [
              {
                name: "Seasonal Artifact mod",
                items: [
                  4186620519, // Oppressive Darkness
                  4186620516, // Solar Plexus
                  4186620517, // Heavy Finisher
                  4186620514, // Volatile Conduction
                  4186620515 // Guardian Angel
                ]
              },
              {
                name: "General",
                items: [
                  3320641683, // Absolution
                  1513970148, // Distribution
                  4237638090, // Special Finisher
                  4237638094 // Snapload Finisher
                ]
              }
            ]
          },
          {
            name: "Arc",
            nameHash: 728351493,
            itemGroups: [
              [
                1432806784, // Invigoration
                3974455041, // Outreach
                4237638091, // One-Two Finisher
                4237638095, // Explosive Finisher
                3065699930, // Hands-On
                4092923892, // Pump Action
                1957851633, // Bleeding Edge
                4121395272 // Storm of Lead
              ]
            ],
            groups: [
              {
                name: "General",
                items: [
                  1432806784, // Invigoration
                  3974455041, // Outreach
                  4237638091, // One-Two Finisher
                  4237638095, // Explosive Finisher
                  3065699930, // Hands-On
                  4092923892, // Pump Action
                  1957851633, // Bleeding Edge
                  4121395272 // Storm of Lead
                ]
              }
            ]
          },
          {
            name: "Solar",
            nameHash: 591714140,
            itemGroups: [
              [
                2476831315, // Recuperation
                3598368346, // Innervation
                3561960031, // Bomber
                3884084138, // Enhanced Bomber
                322752304, // Ashes to Assets
                3320253353, // Enhanced Ashes to Assets
                4084428384, // Light Reactor
                2548337781, // Blast Off
                1834598430 // Light Conductor
              ]
            ],
            groups: [
              {
                name: "General",
                items: [
                  2476831315, // Recuperation
                  3598368346, // Innervation
                  3561960031, // Bomber
                  3884084138, // Enhanced Bomber
                  322752304, // Ashes to Assets
                  3320253353, // Enhanced Ashes to Assets
                  4084428384, // Light Reactor
                  2548337781, // Blast Off
                  1834598430 // Light Conductor
                ]
              }
            ]
          },
          {
            name: "Void",
            nameHash: 4069572561,
            itemGroups: [
              [
                1320020854, // Better Already
                973776237, // Insulation
                4137020505, // Perpetuation
                1016705548, // Dynamo
                4237638088, // Bulwark Finisher
                4237638089, // Healthy Finisher
                2375300279, // Remote Connection
                3962384413 // Dire Artillery
              ]
            ],
            groups: [
              {
                name: "General",
                items: [
                  1320020854, // Better Already
                  973776237, // Insulation
                  4137020505, // Perpetuation
                  1016705548, // Dynamo
                  4237638088, // Bulwark Finisher
                  4237638089, // Healthy Finisher
                  2375300279, // Remote Connection
                  3962384413 // Dire Artillery
                ]
              }
            ]
          }
        ]
      },
      {
        name: "Universal",
        big: true,
        sections: [
          {
            name: "Any",
            nameHash: 1198124803,
            itemGroups: [
              [
                3465659110 // Prized Shooting
              ],
              [
                4048838440, // Discipline Mod
                3253038666, // Strength Mod
                3355995799, // Intellect Mod
                3961599962, // Mobility Mod
                2645858828, // Recovery Mod
                2850583378, // Resilience Mod
                531752975, // Minor Resist
                1313760467, // Major Resist
                1719752237, // Boss Resist
                2588939505 // Concussive Dampener
              ],
              [
                3895804619, // Dreambane Mod
                3630287380, // Enhanced Relay Defender
                3415291596 // Relay Defender
              ],
              [
                2859541905, // Taken Armaments
                399528760, // Taken Invigoration
                3570105787, // Taken Barrier
                2589105944 // Taken Repurposing
              ],
              [
                2503471403, // Fallen Armaments
                3395883122, // Fallen Invigoration
                3099724909, // Fallen Barrier
                2276366746 // Fallen Repurposing
              ],
              [
                2816649701, // Striking Hand
                499567183, // Shielding Hand
                2280136185, // Giving Hand
                1489470244, // Power Overwhelming
                4130296084, // Energized
                927348227, // Hive Armaments
                2146600970, // Hive Invigoration
                3967424085, // Hive Barrier
                3302924434 // Hive Repurposing
              ],
              [
                3632726238, // Taking Charge
                3632726239, // Shield Break Charge
                3632726236, // Empowered Finish
                3632726237 // High-Energy Fire
              ],
              [
                179977572 // Global Reach
              ]
            ],
            groups: [
              {
                name: "Seasonal Artifact mod",
                items: [
                  3465659110 // Prized Shooting
                ]
              },
              {
                name: "General",
                items: [
                  4048838440, // Discipline Mod
                  3253038666, // Strength Mod
                  3355995799, // Intellect Mod
                  3961599962, // Mobility Mod
                  2645858828, // Recovery Mod
                  2850583378, // Resilience Mod
                  531752975, // Minor Resist
                  1313760467, // Major Resist
                  1719752237, // Boss Resist
                  2588939505 // Concussive Dampener
                ]
              },
              {
                name: "Seasonal Mod: Undying",
                items: [
                  3895804619, // Dreambane Mod
                  3630287380, // Enhanced Relay Defender
                  3415291596 // Relay Defender
                ]
              },
              {
                name: "Seasonal Mod: Outlaw",
                items: [
                  2859541905, // Taken Armaments
                  399528760, // Taken Invigoration
                  3570105787, // Taken Barrier
                  2589105944 // Taken Repurposing
                ]
              },
              {
                name: "Seasonal Mod: Forge",
                items: [
                  2503471403, // Fallen Armaments
                  3395883122, // Fallen Invigoration
                  3099724909, // Fallen Barrier
                  2276366746 // Fallen Repurposing
                ]
              },
              {
                name: "Seasonal Mod: Opulence",
                items: [
                  2816649701, // Striking Hand
                  499567183, // Shielding Hand
                  2280136185, // Giving Hand
                  1489470244, // Power Overwhelming
                  4130296084, // Energized
                  927348227, // Hive Armaments
                  2146600970, // Hive Invigoration
                  3967424085, // Hive Barrier
                  3302924434 // Hive Repurposing
                ]
              },
              {
                name: "Seasonal Mod: Dawn",
                items: [
                  3632726238, // Taking Charge
                  3632726239, // Shield Break Charge
                  3632726236, // Empowered Finish
                  3632726237 // High-Energy Fire
                ]
              },
              {
                name: "Seasonal Mod: Worthy",
                items: [
                  179977572 // Global Reach
                ]
              }
            ]
          },
          {
            name: "Arc",
            nameHash: 728351493,
            itemGroups: [
              [
                3074491624 // Arc Resistance
              ],
              [
                3829100654, // Supreme Nightmare Banisher
                1996040463, // Enhanced Nightmare Banisher
                2874957617, // Nightmare Banisher
                2037533514, // Enhanced Resistant Tether
                2887845822 // Resistant Tether
              ],
              [
                4240256197, // Empowering Largesse
                1409526707 // Emperor's Shock
              ],
              [
                1484685884, // Quick Charge
                1484685885, // Striking Light
                1484685886, // Heavy Handed
                1484685887 // Powerful Friends
              ],
              [
                179977573, // Blessing of Rasputin
                179977575, // Warmind's Light
                1789319806, // Modular Lightning
                1789319807, // Strength of Rasputin
                1789319804, // Sheltering Energy
                1789319805 // Chosen of the Warmind
              ],
              [
                2979815164, // Swift Charge
                2979815165, // Lucent Blade
                2979815166, // Font of Light
                2979815167 // Radiant Light
              ]
            ],
            groups: [
              {
                name: "General",
                items: [
                  3074491624 // Arc Resistance
                ]
              },
              {
                name: "Seasonal Mod: Undying",
                items: [
                  3829100654, // Supreme Nightmare Banisher
                  1996040463, // Enhanced Nightmare Banisher
                  2874957617, // Nightmare Banisher
                  2037533514, // Enhanced Resistant Tether
                  2887845822 // Resistant Tether
                ]
              },
              {
                name: "Seasonal Mod: Opulence",
                items: [
                  4240256197, // Empowering Largesse
                  1409526707 // Emperor's Shock
                ]
              },
              {
                name: "Seasonal Mod: Dawn",
                items: [
                  1484685884, // Quick Charge
                  1484685885, // Striking Light
                  1484685886, // Heavy Handed
                  1484685887 // Powerful Friends
                ]
              },
              {
                name: "Seasonal Mod: Worthy",
                items: [
                  179977573, // Blessing of Rasputin
                  179977575, // Warmind's Light
                  1789319806, // Modular Lightning
                  1789319807, // Strength of Rasputin
                  1789319804, // Sheltering Energy
                  1789319805 // Chosen of the Warmind
                ]
              },
              {
                name: "Seasonal Mod: Arrivals",
                items: [
                  2979815164, // Swift Charge
                  2979815165, // Lucent Blade
                  2979815166, // Font of Light
                  2979815167 // Radiant Light
                ]
              }
            ]
          },
          {
            name: "Solar",
            nameHash: 591714140,
            itemGroups: [
              [
                1429600943 // Solar Resistance
              ],
              [
                2023980600, // Supreme Nightmare Breaker
                4193902249, // Enhanced Nightmare Breaker
                1560574695, // Nightmare Breaker
                4020036031, // Enhanced Voltaic Ammo Collector
                928186993 // Voltaic Ammo Collector
              ],
              [
                2689994974, // Radiant Largesse
                4018667352 // Emperor's Blaze
              ],
              [
                3185435909, // Heal Thyself
                3185435908, // Firepower
                3185435911, // Blast Radius
                3185435910 // Charged Up
              ],
              [
                179977574, // Light of the Fire
                2216063963, // Burning Cells
                2216063962, // Wrath of Rasputin
                2216063961, // Fireteam Medic
                2216063960, // Rage of the Warmind
                2216063967 // Incinerating Light
              ],
              [
                4272180933, // Sustained Charge
                4272180932, // Argent Ordnance
                4272180935, // Kindling the Flame
                4272180934 // Supercharged
              ]
            ],
            groups: [
              {
                name: "General",
                items: [
                  1429600943 // Solar Resistance
                ]
              },
              {
                name: "Seasonal Mod: Undying",
                items: [
                  2023980600, // Supreme Nightmare Breaker
                  4193902249, // Enhanced Nightmare Breaker
                  1560574695, // Nightmare Breaker
                  4020036031, // Enhanced Voltaic Ammo Collector
                  928186993 // Voltaic Ammo Collector
                ]
              },
              {
                name: "Seasonal Mod: Opulence",
                items: [
                  2689994974, // Radiant Largesse
                  4018667352 // Emperor's Blaze
                ]
              },
              {
                name: "Seasonal Mod: Dawn",
                items: [
                  3185435909, // Heal Thyself
                  3185435908, // Firepower
                  3185435911, // Blast Radius
                  3185435910 // Charged Up
                ]
              },
              {
                name: "Seasonal Mod: Worthy",
                items: [
                  179977574, // Light of the Fire
                  2216063963, // Burning Cells
                  2216063962, // Wrath of Rasputin
                  2216063961, // Fireteam Medic
                  2216063960, // Rage of the Warmind
                  2216063967 // Incinerating Light
                ]
              },
              {
                name: "Seasonal Mod: Arrivals",
                items: [
                  4272180933, // Sustained Charge
                  4272180932, // Argent Ordnance
                  4272180935, // Kindling the Flame
                  4272180934 // Supercharged
                ]
              }
            ]
          },
          {
            name: "Void",
            nameHash: 4069572561,
            itemGroups: [
              [
                107977982 // Void Resistance
              ],
              [
                2045123179, // Supreme Nightmare Crusher
                1565861116, // Enhanced Nightmare Crusher
                3736152098, // Nightmare Crusher
                865380761, // Enhanced Voltaic Mote Collector
                4134680615 // Voltaic Mote Collector
              ],
              [
                4185864113, // Embraced Largesse
                301151651 // Emperor's Balance
              ],
              [
                3523075120, // Protective Light
                3523075121, // Extra Reserves
                3523075122, // Precisely Charged
                3523075123 // Stacks on Stacks
              ],
              [
                179977568, // Grasp of the Warmind
                2597888510, // Cellular Suppression
                2597888511, // Power of Rasputin
                2597888508, // Warmind's Protection
                2597888509, // Warmind's Longevity
                2597888506 // Light from Darkness
              ],
              [
                2263321584, // Precision Charge
                2263321585, // Surprise Attack
                2263321586, // Energy Converter
                2263321587 // Charge Harvester
              ]
            ],
            groups: [
              {
                name: "General",
                items: [
                  107977982 // Void Resistance
                ]
              },
              {
                name: "Seasonal Mod: Undying",
                items: [
                  2045123179, // Supreme Nightmare Crusher
                  1565861116, // Enhanced Nightmare Crusher
                  3736152098, // Nightmare Crusher
                  865380761, // Enhanced Voltaic Mote Collector
                  4134680615 // Voltaic Mote Collector
                ]
              },
              {
                name: "Seasonal Mod: Opulence",
                items: [
                  4185864113, // Embraced Largesse
                  301151651 // Emperor's Balance
                ]
              },
              {
                name: "Seasonal Mod: Dawn",
                items: [
                  3523075120, // Protective Light
                  3523075121, // Extra Reserves
                  3523075122, // Precisely Charged
                  3523075123 // Stacks on Stacks
                ]
              },
              {
                name: "Seasonal Mod: Worthy",
                items: [
                  179977568, // Grasp of the Warmind
                  2597888510, // Cellular Suppression
                  2597888511, // Power of Rasputin
                  2597888508, // Warmind's Protection
                  2597888509, // Warmind's Longevity
                  2597888506 // Light from Darkness
                ]
              },
              {
                name: "Seasonal Mod: Arrivals",
                items: [
                  2263321584, // Precision Charge
                  2263321585, // Surprise Attack
                  2263321586, // Energy Converter
                  2263321587 // Charge Harvester
                ]
              }
            ]
          }
        ]
      }
    ]
  }
];
